# Use an official Nginx image to serve the website
FROM nginx:alpine

# Copy the static website files into the Nginx web directory
COPY index.html /usr/share/nginx/html/

# Expose port 80 to allow access to the web server
EXPOSE 90

