version: '3.8'

services:
  app:
    build: .
    ports:
      - "9090:9090"
    container_name: mens-clothing-store
    restart: always
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    restart: always

