pipeline {
    agent any 

    environment {
        docker_image = "selvavignesh02/grocery-ordering:latest"
    }

    stages {
        stage ('checkout repository') {
            steps {
                checkout scm
            }
        }

        stage ('Build Grocery Image-Docker') {
            steps {
                sh 'docker build -t ${docker_image} .'
            }
        }

        stage ('Running Container') {
            steps {
                sh 'docker run -d -p 9090:5000 --name grocery-container ${docker_image}'
            }
        }
    }

    post {
        success {
            echo "Running the Grocery container successfully."
        }
        failure {
            echo "Failed to build or run the container."
        }
    }
}

