pipeline {
    agent any
    
    stages {
        stage('Docker Image Build') {
            steps {
                sh 'docker build -t selvavignesh02/pythonapp:latest myapp'
            }
        }
        stage('Run Docker Container') {
            steps {
                sh 'docker run -d -p 9090:9090 --name my-image selvavignesh02/pythonapp:latest'
            }
        }
    }

    post {
        success {
            echo "Build succeeded and the container is running."
        }
        failure {
            echo "Failed to build the Docker image or run the container."
        }
    }
}

